name: startupnamer
description: A new Flutter application.

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.3

  english_words: ^3.1.5

  audioplayers: ^0.15.1

  # use this package in quizzler when all questions are finished.
  rflutter_alert: ^1.0.3

  # use these packages below in Timer project
  flutter_bloc: ^4.0.0
  equatable: ^1.0.0
  wave: ^0.0.8

  font_awesome_flutter: ^8.8.1

  # use this package in Clima (Angela used 3.0.1 in the lecture)
  geolocator: ^5.3.2+2
  # use this package for network request
  http: ^0.12.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - images/
    - assets/

  fonts:
    - family: Pacifico
      fonts:
        - asset: fonts/Pacifico-Regular.ttf

    - family: Source Sans Pro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf

    - family: Spartan MB
      fonts:
        - asset: fonts/SpartanMB-Black.otf
          weight: 900